# Generated by Django 4.1.7 on 2023-08-16 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_rename_group_chatgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatGroup',
            new_name='GroupChat',
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(choices=[('p', 'personal'), ('g', 'group')], max_length=30),
        ),
    ]
