# Generated by Django 4.1.7 on 2023-08-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_links_link_alter_link_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
    ]
